'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Producto
    Public Property ProductoID As Integer
    Public Property Nombre As String
    Public Property Precio As Decimal
    Public Property Stock As Integer
    Public Property CategoriaID As Integer

    Public Overridable Property CategoriaProducto As CategoriaProducto
    Public Overridable Property DetalleVenta As ICollection(Of DetalleVenta) = New HashSet(Of DetalleVenta)

End Class
