'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class TiendaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TiendaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property CategoriaProducto() As DbSet(Of CategoriaProducto)
    Public Overridable Property Ciudad() As DbSet(Of Ciudad)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property DetalleVenta() As DbSet(Of DetalleVenta)
    Public Overridable Property Producto() As DbSet(Of Producto)
    Public Overridable Property TipoPago() As DbSet(Of TipoPago)
    Public Overridable Property Venta() As DbSet(Of Venta)

    <DbFunction("TiendaEntities", "fn_VentasPorCliente")>
    Public Overridable Function fn_VentasPorCliente(id As Nullable(Of Integer)) As IQueryable(Of fn_VentasPorCliente_Result)
        Dim idParameter As ObjectParameter = If(id.HasValue, New ObjectParameter("id", id), New ObjectParameter("id", GetType(Integer)))

         Return DirectCast(Me, IObjectContextAdapter).ObjectContext.CreateQuery(Of fn_VentasPorCliente_Result)("[TiendaEntities].[fn_VentasPorCliente](@id)", idParameter)
    End Function

End Class
