'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoPago
    Public Property TipoPagoID As Integer
    Public Property Descripcion As String
    Public Property EstaActivo As String

    Public Overridable Property Venta As ICollection(Of Venta) = New HashSet(Of Venta)

End Class
