'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venta
    Public Property VentaID As Integer
    Public Property FechaVenta As Date
    Public Property ClienteID As Integer
    Public Property TipoPagoID As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property DetalleVenta As ICollection(Of DetalleVenta) = New HashSet(Of DetalleVenta)
    Public Overridable Property TipoPago As TipoPago

End Class
